### ISSUE TITLE
Savestates for 2 games

### ISSUE THREAD

**Issue by sp1ashe** [poliva/fightcadestates#10]
Here are new savestate files for following two games. I want it included in the next update:

vampjr1_ggpo.fs - Vampire: The Night Warriors (Japan 940630)
vhuntjr2_ggpo.fs - Vampire Hunter: Darkstalkers' Revenge (Japan 950302)

https://mega.co.nz/#F!ydQxUThZ!15Q_5poeuks4ud2xXYO_NQ

**Comment by Utop** [comment]
Hello,

Vampire Hunter (950302 Japan) works without desynch in the Night Warriors - darkstalkers' revenge room (950316 Euro) with sp1ashe's savestate, the same applies to Vampire (940630 Japan).

But we have 3 problems:
-the main problem is for replays, it doesn't works;
-we are not able to launch Vampire Hunter or Vampire in "Unsuported games" rooms, we tried ggpo tutos in vain;
-lastly, like 3xcl4m4t10n said, fightcade resets the savestate at every start. However it is not so annoying.

Do you have any solutions? Thanks in advance for your assistance.

**Comment by 3xcl4m4t10n** [comment]
I was playing there over and the people is happy with the roms and savestates as they are. If you want to bring me more feedback you are free to do it but i think it is ok as it is now.

**Comment by poliva** [comment]
Closing this issue. Please reopen if this needs attention again.
