### ISSUE TITLE
KOF2000 always desyncs

### ISSUE THREAD

**Issue by leepc12** [poliva/fightcadestates#12]
People in channel kof2000 all have the same desync issue. They are using the same rom that was used for ggpo without no issue. We got the following popup error and the game language is set to japanese and it desyncs in a couple of games.

kof2000.zip was found (ROM_PATH\kof2000.zip)
neogeo.zip was found (ROM_PATH\neogeo.zip)

The ROMset is OK.Error loading neo-epo.bin, requested by kof2000.
The emulation will likely suffer problems.

I found that kof2000 with ggpofba.exe runs well without the warning.

**Comment by poliva** [comment]
is this still a problem?

**Comment by 3xcl4m4t10n** [comment]
No, it was fixed with the last savestate.
