### ISSUE TITLE
Request for savestates adjustment for 2 games (sfiiin / sfiii2n)

### ISSUE THREAD

**Issue by Geckoin1** [poliva/fightcadestates#21]
Games: Street Fighter III: New Generation & 2nd Impact.

Issue: Character voices doesn't sound traditional enough. Alternative voices sounds weird and lacking. 

Solution: F2 > Config > System > Voice type should be turned on. 

Also, enable free play, please & thanks.

**Comment by 3xcl4m4t10n** [comment]
Ok, i will make the new savestates later tonight. Thanks for the feedback.

**Comment by poliva** [comment]
@3xcl4m4t10n a reminder for you to do sfiii2n_ggpo.fs and sfiiin_ggpo.fs with the changes proposed by @Geckoin1

**Comment by 3xcl4m4t10n** [comment]
Thanks for the reminder! I will make it in some hours so you can add this one to the list ;D.

**Comment by 3xcl4m4t10n** [comment]
Ok :

https://mega.co.nz/#!3ZUwRYjI!MCXTTUphn81-X54e9zKqy1qzwDki80UYpXS--nPm7a8
https://mega.co.nz/#!XIlD2J7R!9qQAibJtjA0CuEANdQLQmh6wvIuzCAZNkN6-P2_Iu5s

Remember to try it on Fightcade client against another player NOT on FBA. Tell me the results please :D.

**Comment by Geckoin1** [comment]
So, yeah........................when will these savestates be released (or updated)? lol.

**Comment by poliva** [comment]
@Geckoin1 have u tried the savestates? if you're happy with the results I can push them in the next server restart

**Comment by Geckoin1** [comment]
I tried them, and I'm satisfied. Thanks  :)

**Comment by poliva** [comment]
changes are live

**Comment by poliva** [comment]
Looks like there's something wrong with those updated savestates too, please see: https://github.com/poliva/pyqtggpo/issues/14
/cc @3xcl4m4t10n

**Comment by poliva** [comment]
@Geckoin1 is the issue happening to everyone? just want to make sure that both you and the other player have had the savestates files updated by the client automatically when you started it. That black screen issue like you comment can happen if both players use a different savestate (old and new).

**Comment by 3xcl4m4t10n** [comment]
I will check tonight again but is strange because you tried and told us that i had no issue. The problem i am having with this game is that actually i can not try the savestate without anybody (in any games the results differ from a live try to a offlive one).

**Comment by Geckoin1** [comment]
@poliva I believe me and my opponent both received the same updated savestates. When I told him that there's a black screen at my end, he replied "same". By the way, the player's ID is "secretary", and he's from England.

**Comment by 3xcl4m4t10n** [comment]
I will check it ASAP i finish all the Savestates (that is going to happen, hopefully, tomorrow).

**Comment by poliva** [comment]
Closing issue, if for some reason this is not fixed please reopen.

**Comment by Geckoin1** [comment]
Ok. Here are the links for the updated savestates: 

sfiii2n: https://mega.nz/#!3dczmTZS!2CWObV5YNETFxQkjuoqirMnDveMfQfBMur79lrsijao
sfiiin: https://mega.nz/#!uJ8giZxR!8ITLJyQuxEVfq3kopxCK4jFCbz7_MMEsTu1eznk9_7o

Should have no black screen at the beginning of launch.

**Comment by 3xcl4m4t10n** [comment]
Please, do not duplicate the issue. This is actually solved on #33
