### ISSUE TITLE
Swap jojoba room for japanese version.

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [poliva/fightcadestates#22]
Hello pof!

Can you please change the european version avaible now for the japanese version? I was talking with some people and we want a change. I made a savestate for it:

https://mega.co.nz/#!ydUkXTpL!0Qlm76w27apJrMmfEKoU9gURnnPMno_eB-DCHV3I2m0

Also, can you add this like on the SSF2 room?

**JJBA room has changed to jojoban (Japanese Version), update your roms!**

-!- JoJo's WIKI: http://wiki.standcrash.com/index.php?title=Main_Page

And this new lane with a training mode like on SSF2 room (no roms inside, you can check it :dancer: ):

-!- MAME Training mode: http://tinyurl.com/o3fdpdp

Thank you in advance!

**Comment by poliva** [comment]
Changes done: https://github.com/poliva/ggposrv/commit/0e5764606b5144bd881a4eba8e091d855a08ff82
will be live in the next server restart.

**Comment by 3xcl4m4t10n** [comment]
Sorry for re-open this but can you substitute also the link to the Jojo's WIKI for this?

JJBA: HF's WIKI: http://wiki.standcrash.com

The "Jojo's WIKI" name can be confused with a Wiki for the whole series meanwhile HF is the name of the game (Heritage for future). Also the website direction is too long so this one will be more esthetic.

Thank you so much p0f!

**Comment by 3xcl4m4t10n** [comment]
New training mode with a little thing fixed:

-!- MAME Training mode: http://bit.ly/1AyP0x4
