### ISSUE TITLE
Training mode for JJBA

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [poliva/fightcadestates#23]
Hello p0f,

Can you please put this line on the JJBA room?

-!- MAME Training mode: http://bit.ly/1AyP0x4

It's a MAME training mode with instructions. You can check it but it do not have any "illegal" material on it ;D.

Thank you in advance!

**Comment by poliva** [comment]
Hi,

Sorry but I'm not adding this because it's not a proper training mode, it's just a windows MAME build bundled with the unmodified cheats file from http://www.mamecheat.co.uk and if we add this for this game, people will request the same for every game.
