### ISSUE TITLE
[URGENT] Issue on Breakrev savestate

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [poliva/fightcadestates#25]
Hello P0f,

Idk how but i make a very bad mistake with the new savestate. Please, put this new one ASAP. Thank you and sorry for any inconvenience:

https://mega.co.nz/#!OM9ECaYC!r05UtWvHEWWHu-yDzGMnj3GU4FGgmwx-j3LHBI4NsUk

**Comment by 3xcl4m4t10n** [comment]
Hello again P0f,

I think i had a mental problem or something but i also broke the new jojoban savestate. I'm so sorry for all this issues and hope you can fix it ASAP:

https://mega.co.nz/#!yAlFlaKR!7xNmEULto1UOuBoRadlmzG3fxW5pLU3p6CFZq2Zc-zM

**Comment by poliva** [comment]
Fixed. Please see https://github.com/poliva/fightcadestates/issues/21#issuecomment-75195228 because maybe it might be related to the same problem.
