### ISSUE TITLE
Savestate group "Number IwantTObeONtheSpecialThanksSection".

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [poliva/fightcadestates#28]
magdrop2_ggpo.fs
magdrop3_ggpo.fs
megaman2_ggpo.fs
mercs_ggpo.fs
mmancp2u_ggpo.fs
progear_ggpo.fs
ragnagrd_ggpo.fs
rbff1_ggpo.fs
rbff2_ggpo.fs
rbffspec_ggpo.fs
redeartn_ggpo.fs
s1945p_ggpo.fs
samsh5sp_ggpo.fs
samsho2_ggpo.fs
samsho3_ggpo.fs
samsho4_ggpo.fs
samsho5_ggpo.fs
samsho_ggpo.fs
savagere_ggpo.fs
sengoku2_ggpo.fs
sengoku3_ggpo.fs
sengoku_ggpo.fs
sf2ce_ggpo.fs
sf2hf_ggpo.fs
sf2koryu_ggpo.fs
sf2_ggpo.fs
sfa3_ggpo.fs
sfa_ggpo.fs
sfiii3an_ggpo.fs
vampjr1_ggpo.fs
vhuntjr2_ggpo.fs

https://mega.co.nz/#F!yBtXVDAK!bGBjE--c6vg_5GAbXXeYOA

I dropped vampjr1_ggpo.fs and vhuntjr2_ggpo.fs as the people request but made some "aesthetical" corrections. If i am right, I only left 20 savestates now to finish :D.

**Comment by poliva** [comment]
23:37 <Sixtyten> pof i'm sorry to bother you but i noticed you changed the sfa3 savestate for some reason, however now you have done that all the extras that are under a time lock are missing, 3 characters are no longer selectable and also classic mode is missing, can you please revert back to the old savestate as a few people play the hidden characters as their mains

**Comment by Sixtyten** [comment]
Hi I am the a3 player poliva is referencing in his comment, street fighter alpha 3 has several modes and 3 hidden characters which are on a time lock, meaning that after a certain amount of uptime the arcade cabinet has it will unlock different content. There are codes that can be input to automatically unlock all the content, http://strategywiki.org/wiki/Street_Fighter_Alpha/Secrets#Street_Fighter_Alpha_3
If you follow these instructions to unlock the content and test whether the content is unlocked then change the savestate to that one that would be great, however you could also just revert back to the ggpo savestate as it was perfect, it already has everything unlocked.

**Comment by 3xcl4m4t10n** [comment]
Hello Sixtyten,

I am going to use the actual savestate with the unlocked content. Also, can you tell me some additional feature? Like the TURBO selection or something more to correct? Thank you!

**Comment by Sixtyten** [comment]
Turbo 2 is the standard, nothing else needs to be done, just the unlocked content, and the speed set to turbo 2. Thanks

**Comment by 3xcl4m4t10n** [comment]
Ok, i made it. I will upload later with another group of savestates. Just try when it is live on the client and tell me if everything is all right. I try by myself and all the characters and modes are working but a double-check would be very fine. Thank you for the report!

**Comment by 3xcl4m4t10n** [comment]
Solved at #31.
