### ISSUE TITLE
All Metal Slugs Savestates with Blood active

### ISSUE THREAD

**Issue by IoriX2k2** [poliva/fightcadestates#29]
I am requesting to activate the blood in all metal slug save states savestates (I think Metal Slug X has blood active on its save).

**Comment by poliva** [comment]
cc @3xcl4m4t10n

**Comment by 3xcl4m4t10n** [comment]
Hello IoriX2k2,

The Metal Slug savestates are not updated yet but one of the features will be, of course, the activation of blood. If everything goes right and as i said on #28, it will be today avaible :D.

**Comment by IoriX2k2** [comment]
omg, you're my hero, the world will be so much more happy, =).

**Comment by 3xcl4m4t10n** [comment]
Yeah, the world will be more happy with more blood (·A·). Solved at #31
