### ISSUE TITLE
Savestate group "Finish Him!"

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [poliva/fightcadestates#31]
I can't believe that I already finished the almost 200 savestates :__D.

mmatrix_ggpo.fs
mpang_ggpo.fs
ms5plus_ggpo.fs
mshvsf_ggpo.fs
msh_ggpo.fs
mslug2_ggpo.fs
mslug3b6_ggpo.fs
mslug3_ggpo.fs
mslug4_ggpo.fs
mslugx_ggpo.fs
mslug_ggpo.fs
msword_ggpo.fs
mutnat_ggpo.fs
ncombat_ggpo.fs
ncommand_ggpo.fs
neobombe_ggpo.fs
neocup98_ggpo.fs
ninjamas_ggpo.fs
nitd_ggpo.fs
sfa3_ggpo.fs

https://mega.co.nz/#F!HYdFDJTK!jPK1HXt5k_hxANqD2qFL8g

**Comment by 3xcl4m4t10n** [comment]
Added:

slammast_ggpo.fs
zupapa_ggpo.fs

**Comment by poliva** [comment]
all savestates have been updated, thanks for your hard work @3xcl4m4t10n !!!!111one
