### ISSUE TITLE
Savestate Windjammers 99sec

### ISSUE THREAD

**Issue by Dobodry** [poliva/fightcadestates#32]
I send you a savestate for windjammers in 99 sec and UK settings for gain time and Steve Miller remplace B.Yoo.

wjammers_ggpo.fs

https://1fichier.com/?rauim2br6l

**Comment by 3xcl4m4t10n** [comment]
Why UK and not Korea? O_o

**Comment by Dobodry** [comment]
haha ok, but just for B.yoo and Miller, steve Miller is the real character, it's a running gag from data east you can find him in a lot of data east game.

http://www.arcade-history.com/index.php?page=person&name=Steve+Miller

 Steve Miller is credited on windjammers to, and on japanese version, the first version of the game, you can't play B. yoo because it's was added for korean market like a lot of game in this period like Heavy Smash, Power spike or soccer brawl.
BTW thanks for you answer I hope most of people who play on fightcade understand this change :)

**Comment by 3xcl4m4t10n** [comment]
That's a nice solid reason, I will put Steve Miller :D. ASAP I ask tomorrow to the people i will made a decision and update the savestate.

**Comment by Dobodry** [comment]
Nice thx man, Have you ask some people for change timer ? I'v ask some players who play seriously and regulary WJ and for the moment all answers is positive to change time :D.

**Comment by Exosta** [comment]
Hi, I'm a regular player (and truly better than Dobodry) on Windjammers too and having this savestate will be a great thing. All our matches are on 99 seconds, whether freeplay or competition, and we have to configure this for every starting challenge, not very useful for sure. And even for casual players, we must explain to them how to go in the bios, configure soft dip, etc.
So we are waiting you in the best game's room for confirmation.

And thanks you for keeping this savestates updated.

**Comment by hanasu** [comment]
What do you have to do to get the settings to save? Upon game reset it's still 30 seconds for me. If you can explain the process I'll make a push request with the update ASAP.

**Comment by hanasu** [comment]
Never mind, it seems to be working now. I'll make the request now.

**Comment by hanasu** [comment]
Try the state in this repository to make sure everything works okay. https://github.com/hanasu/fightcadestates

**Comment by Exosta** [comment]
It doesn't seem to work. Dobodry uploaded a savestate which is working and yours is not the same. Can you try with his ?

**Comment by hanasu** [comment]
Where is the one you say is working? You will need the updated JSON so that the new state will be used. If you do not it still try to load the old one.

**Comment by Exosta** [comment]
On the Dobodry's original post. I don't think it's mandatory to update the JSON for using another savestate : I tried with a player to use the Dobodry's and it worked. Maybe it's just for server to keep all the savestates updated.

**Comment by hanasu** [comment]
That one seems to work for me, if it has been already tested I will use it.

**Comment by hanasu** [comment]
https://github.com/poliva/fightcadestates/pull/37

**Comment by Exosta** [comment]
All lazy Windjammers players will be happy, thanks !

**Comment by 3xcl4m4t10n** [comment]
Ok, i will make in some minutes a definitive savestate with all the requirements from the community and from FightCade. Stay alert :D.

**Comment by Exosta** [comment]
Out of curiosity, what is wrong with the Dobodry's savestate ?

**Comment by 3xcl4m4t10n** [comment]
- Start at mainscreen not at 2P mode (remember FightCade is a multiplayer).
- No level 8.
- Show level.
- Show credit.
- Only 6 credits.

All the games at FC have this common configuration :D.

**Comment by Exosta** [comment]
Ok, I get it. It will be a good idea to have this requirements on the main page of this repository for future pull requests.

**Comment by 3xcl4m4t10n** [comment]
Don't worry, i make all the savestates so i can take care on it ;).

**Comment by hanasu** [comment]
That is a bad attitude to have for future contributors to a project.

**Comment by 3xcl4m4t10n** [comment]
Hanasu this is not an opinion thread, but i do not want to have a bad attitude at you so here it is my last answer about this theme on this topic: It is not a bad attitude. The requirements are published and anyone can send it via Github (as dobodry and others made).

Please, let's continue with the main theme. Remember that this is not a forum.

**Comment by Exosta** [comment]
I uploaded the savestate with the requirements posted by 3xcl4m4t10n : https://1fichier.com/?qs8mdze3md
With its SHA-256 checksum for index.json : 164285e3c9cabeb1fe27c95cc64fa291c6915be29d27b99d4a7563a95e90ee52
hanasu, can you modify your pull request with this one, please ?

(A little disgression for 3xcl4m4t10n : it's a good thing for open projects to have all the requirements published. Thanks to that, we are not depending on only one person and the project can progress on the best way. So thank you for posting it ands thank you for your past - and future - uploads o/)

**Comment by 3xcl4m4t10n** [comment]
Exotar, thanks for the save state but p0f already have the right one (it's pretty similar to yours ;D).

About the save state non-sense-controversy, do not misunderstand me, I agree with the idea to have the requirements made public, in fact, they are available from the first day. My position is that i actually love the p2p gaming and i am very "delicate" with the save states thing. I do not have anything against the people share the save states but i like to check it before get into a public release :D.

For example, the Exosta savestate is near perfect for me, it only lacks 1 or 2 frames after the beggining of the game.

**Comment by poliva** [comment]
Fixed, sorry I've been quite busy and it took a while.
