### ISSUE TITLE
Can't Change controls on Mac version

### ISSUE THREAD

**Issue by hsien-ko** [poliva/fightcadestates#34]
Hi, I like fightcade a lot and used it when I owned a PC, but now that I have a Mac, I have a problem.  I want to use a controller, but I can't get the game to change controller settings through Wine.  Is this just user error or something more?

**Comment by hanasu** [comment]
This is the wrong repository to be asking this in, I've posted it here so more eyes will see it: https://github.com/poliva/pyqtggpo/issues/15

**Comment by poliva** [comment]
you probably need to install a driver for your controller, for example to get my XBox 360 Madcatz Fightstick Pro controller recognized on OS X yosemite I had to install this kernel driver: https://github.com/d235j/360Controller 

Once you get the driver for your fightstick or gamepad installed, then just setup the inputs by pressing F5 with the emulator open.

**Comment by janmchan** [comment]
When you open the game, it's in the top left corner of the screen just like what you would have in windows. Just click on it even though it is not visible. I don't know how to save it though.
![screen shot 2017-02-06 at 10 41 23 am](https://cloud.githubusercontent.com/assets/8134768/22630129/db35b750-ec58-11e6-97de-3d1f14aaf43d.png)
.
