### ISSUE TITLE
Can't launch Fightcade on Mac

### ISSUE THREAD

**Issue by spicadelcielo** [poliva/fightcadestates#35]
Good evening and sorry for the bothering, but it happen that I downloaded Fightcade on mac, but I can't open it. Because it quickly closes itself before I can do anything, and it is constantly happening. Here is the report. 

Process:         fightcade [1496]
Path:            /Applications/FightCade.app/Contents/MacOS/fightcade
Identifier:      fightcade
Version:         0.0.0 (???)
Code Type:       X86-64 (Native)
Parent Process:  fightcade [1495]
Responsible:     sh [1489]
User ID:         501

Date/Time:       2015-03-06 19:01:34.094 +0100
OS Version:      Mac OS X 10.9.4 (13E28)
Report Version:  11
Anonymous UUID:  2C1F999B-B463-1259-C42E-18E101630D11

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00000000003d5fb8  rcx: 0x0000000000000000  rdx: 0x0000000000000054
  rdi: 0x00000000003d5fb8  rsi: 0x0000000000000100  rbp: 0x00007fff5fbfdf90  rsp: 0x00007fff5fbfdf80
   r8: 0x00000000003d5ba0   r9: 0x34c8a31b3a4542db  r10: 0x0000000000000072  r11: 0x0000000001b1bf84
  r12: 0x0000000000000000  r13: 0x00000000003c2a20  r14: 0x00000000002285c0  r15: 0x0000000000000000
  rip: 0x00000000003d02ef  rfl: 0x0000000000010246  cr2: 0x00000000003d02e0
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1750
    thread_create: 1
    thread_set_state: 0

Model: iMac9,1, BootROM IM91.008D.B08, 2 processors, Intel Core 2 Duo, 2.66 GHz, 8 GB, SMC 1.44f0
Graphics: NVIDIA GeForce 9400, NVIDIA GeForce 9400, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x029E, 0x434D5341344758334D314131303636433720
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x029E, 0x434D5341344758334D314131303636433720
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 4.2.6f1 14216, 3 services, 15 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: Hitachi HDT721032SLA380, 320,07 GB
Serial ATA Device: HL-DT-ST DVDRW  GA11N
USB Device: Built-in iSight
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Laser Mouse
USB Device: Generic USB Hub
USB Device: PS3/USB Corded Gamepad
USB Device: IR Receiver
Thunderbolt Bus: 

I would like you to help me to open it without it closing by itself. Thanks for the attention.

**Comment by hanasu** [comment]
This is not a savestate issue. I have asked your question here: https://github.com/poliva/pyqtggpo/issues/18 where you will get more help.

**Comment by spicadelcielo** [comment]
Thank you hanasu.
