### ISSUE TITLE
The King of Dragons US 910910 version request

### ISSUE THREAD

**Issue by drokmar3** [poliva/fightcadestates#38]
Hi. I was wondering is it possible please to change the version of The King of Dragons from the current World 910711 to US 910910. 

The US 910910 version is more challenging with less food, more enemies and tougher bosses with slightly different attack patterns e.g. in the US version the final boss Gildiss chases you across the screen with fiery breath each time he changes position and there are rocks falling during the battle. Also there is music during the attract mode, some new music during the final boss battle, a longer end sequence and various other small changes e.g. crows flying in stage 2.

I've spoken to a few other KOD players on FightCade and they agree with me. 

I completed the US version twice with another player in the unsupported room using this save state: 
https://www.mediafire.com/?nzlmf86tas7az4s

**Comment by 3xcl4m4t10n** [comment]
+1 to this change. I will make the Savestate if p0f have the time to put the other version so don't worry about that ;D.

**Comment by drokmar3** [comment]
Thank you 3xcl4m4t10n.

If p0f has time to change the version I would be grateful.

Would be good if the difficulty setting is set to 'normal' please. I noticed some CP System games on FightCade are set to the easiest difficulty setting. You can of course change the difficulty in the dipswitches but I think it's better if games are set to the true default difficulty as they normally would be in an arcade.

**Comment by poliva** [comment]
hey @3xcl4m4t10n send me the savestate and i'll make the change.

**Comment by drokmar3** [comment]
moltes gràcies!

**Comment by poliva** [comment]
changes will be live on the next server restart.
