### ISSUE TITLE
[Champion Edition] replace sf2ce -> sf2cej

### ISSUE THREAD

**Issue by poliva** [poliva/fightcadestates#39]
fran3s suggested to change the current <b>sf2ce</b> for <b>sf2cej</b>:
<pre>
2015-03-16 19:42 - &lt;fran3s&gt; for what it's worth , sf II dash / ce should be using the japanese version
2015-03-16 19:42 - &lt;fran3s&gt; the current world / us one is fucked up
2015-03-16 20:16 - &lt;fran3s&gt; i think it's one of the early ones where vega is super broken,sagat's mp and hp uppercut don't knock down etc etc
2015-03-16 20:18 - &lt;fran3s&gt; i think the japanese versions and later us / world revisions are a lot better,that's all
2015-03-16 20:45 - &lt;fran3s&gt; https://www.youtube.com/watch?v=7FS2pxEV8tE
</pre>
Anyone who cares about this game votes for or against this change? what are the reasons? Is <b>sf2cej</b> (Japanese version) the best version to use? or should we use <b>sf2ceub</b>, <b>sf2ceuc</b> (later English revisions, which should not be buggy)?

**Comment by poliva** [comment]
to be clear, the options are the following:
* <b>sf2ce</b>: "Street Fighter II' - champion edition (street fighter 2' 920313 etc)"
* <b>sf2cej</b>: "Street Fighter II' - champion edition (street fighter 2' 920513 Japan)"
* <b>sf2ceua</b>: "Street Fighter II' - champion edition (street fighter 2' 920313 USA)"
* <b>sf2ceub</b>: "Street Fighter II' - champion edition (street fighter 2' 920513 USA)"
* <b>sf2ceuc</b>: "Street Fighter II' - champion edition (street fighter 2' 920803 USA)"

(the first one is the current one on fightcade)

**Comment by ummalucoperdidonanet** [comment]
The version and the most widely played here in south america, China and Korea would be this: sf2ce: "Street Fighter II '- Champion Edition (Street Fighter 2' 920 313 etc)

**Comment by 3xcl4m4t10n** [comment]
I think the most stable version is sf2cej. I can't understand your message, ummalucoperdidonanet.

**Comment by ummalucoperdidonanet** [comment]
Really the japan version, and the most balanced but the most widely played today and the English version of the game, so that even in China and Korea which are in Asia, play this versão.Eu not say for me, but all players the world still playing this version of this street!

**Comment by 3xcl4m4t10n** [comment]
Ok, thanks for the explanation. I got your point, but we must ask to the community to make a decisition ;D

**Comment by hanasu** [comment]
What really matters is what the South American crew say. I've asked them which version they prefer on Facebook but no one has responded. Since that is where the most players play, if we want to promote the game on Fightcade we should pick the one that the largest community uses.

**Comment by sosachile** [comment]
sf2ce: "Street Fighter II' - champion edition (street fighter 2' 920313 etc). This version are played in South Korea, China and South America, the regions that actually play the game (offline and online). Others versions, sucks!!

**Comment by poliva** [comment]
Closing and leaving as it is, as that's what most people who play the game prefers.
