### ISSUE TITLE
[World Warrior] replace sf2 -> sf2ua

### ISSUE THREAD

**Issue by poliva** [poliva/fightcadestates#40]
Jion_Wansu suggested to change the current <b>sf2</b> for <b>sf2ua</b>:
<pre>
08:53 &lt;Jion_Wansu&gt; pof, can you enable Street Fighter II: The World Warrior (USA 910206)? It has harder boss characters than Street Fighter II: The World Warrior (910522 etc))
08:53 &lt;Jion_Wansu&gt; for example, Guile's statue does not work on CPU Claw and CPU Gief
08:54 &lt;Jion_Wansu&gt; CPU Claw just throws Guile instead doing th einfinite slide
08:54 &lt;Jion_Wansu&gt; CPU Dictator has SNK boss syndrome in that game
</pre>
Anyone who cares about this game votes for or against this change? what are the reasons? Is <b>sf2ua</b> (USA 910206 version) the best version to use? or should we use <b>sf2j</b> (Japanese version) or <b>sf2ui</b>, or <b>sf2uk</b> (later English revisions, which should not be buggy)?

**Comment by derkaiser111** [comment]
sf2ua: "Street Fighter II - the world warrior (910206 USA)"

**Comment by poliva** [comment]
Closing and leaving as it is, as there doesn't seem to be a clear winner.
