### ISSUE TITLE
Question: Running Unsupported Games

### ISSUE THREAD

**Issue by Toosterlover** [poliva/fightcadestates#47]
I downloaded FB Alpha and I got just a random save state from a game I was playing just to see if I could test it in the unsupported games section of fightcade. I renamed it to unsupported_ggpo as the instructions stated, and then tried to run the game, but to no avail, I then tried again but with a different game, also no luck. I am not concerned with playing online, so much as I am trying to just get it to run in the first place. Are there any more detailed instructions/tutorials as to how I could get an unsupported game running? What is it that I am getting wrong?

**Comment by 3xcl4m4t10n** [comment]
Why did you downloaded FBAlpha if it is included on Fightcade? I think you are not using the same version that Fightcade is using. But please, explain why did you downloaded another version, I am a little curious.

**Comment by Toosterlover** [comment]
Okay, here's my train of thought. There are some FB Alpha ROMs that I am interested in that are not on fightcade. The Fightcade Unsupported Lobby instructions say that you need to have a savestate of an unsupported game in the savestate folder, and rename it as such. I have FB Alpha, get the ROM that I was interested in and start it up using FB Alpha, not fightcade. On the title screen of the game I create a save state, this makes a .fs file that is the same type of file as all other savestates in the savestate folder. I rename that savestate to 'unsupported_ggpo' and I copy that same savestate from my FB Alpha folder over to the savestate folder in Fightcade, and just to be sure, I also copy that ROM that savestate beloonged to and paste it into Fightcade. Having both an FB Alpha compatible savestate and ROM I try to launch Fightcade, but to no avail.
The reason why I downloaded another version of FB Alpha was so I could run the game separately and create the necessary .fs savestate that the instructions said was needed. Not knowing that it would not run the way it did.
As you can tell I am unclear on the idea of running unsupported games on fightcade.

**Comment by 3xcl4m4t10n** [comment]
You are doing it right but still do not understand why are you using another FBAlpha aside from the included on Fightcade.

**Comment by Toosterlover** [comment]
My confusion was that I thought Fightcade, and the file named 'ggpofba' were initially different applications and that downloading FB Alpha was a different thing entirely, but now looking back on it, if they are the same application, why would a rom work in FB Alpha, but not in fightcade?

**Comment by 3xcl4m4t10n** [comment]
Because FBAlpha used by Fightcade is outdated. The emulation is something that's constantly grown so one version can support a game but it did not mean old versions have to work with the same rom. In some cases the same game can have also different versions. So, if you are going to check any game, do not complicate your life and use the FBAlpha included with Fightcade.

**Comment by Toosterlover** [comment]
Okay, than with that being said, are there any plans to update FB Alpha used by fightcade to expand the possible library?

**Comment by 3xcl4m4t10n** [comment]
https://www.fightcade.com/#faq

**Comment by Toosterlover** [comment]
Much appreciated, thank you for being patient with my ignorance.

**Comment by 3xcl4m4t10n** [comment]
No problem mah boi, it's a pleasure being useful :P.
