### ISSUE TITLE
Cannot connect to fightcade.com on V0.40

### ISSUE THREAD

**Issue by Swigglez1997** [poliva/fightcadestates#53]
So I downloaded the program, I tried to login and it give me this 
![proof](https://cloud.githubusercontent.com/assets/13143330/8784540/7bba5fd2-2ed7-11e5-90ae-75106d6258e5.png)
I tries everything, restarting the program, restarting the computer. I tried to allow all three of the exe in the windows firewall. Nothing work for me, can you help me with this please?

**Comment by 3xcl4m4t10n** [comment]
Did you try to open the ggpo ports?

**Comment by Swigglez1997** [comment]
No i havent, how do i do that ? TY.

**Comment by Swigglez1997** [comment]
GGPO Ports: 6000-6009 UDP, 7000 TCP are these the ports ?

**Comment by 3xcl4m4t10n** [comment]
Yeah, try it and tell us if it worked. BTW what OS are you using?

**Comment by Swigglez1997** [comment]
Windows 8 and I tried it, it didn't work

**Comment by Swigglez1997** [comment]
actually it works after a restart, thx for helping
