### ISSUE TITLE
Sunset Riders

### ISSUE THREAD

**Issue by RaverKai** [poliva/fightcadestates#54]
This game is amazing, coop/shooter yeeeeja

**Comment by ecayazzo** [comment]
While Fightcade is using the 0.2.96.74 version of FB Alpha, this is impossible.
Sunset Riders was added to the Konami drivers just in the 0.2.97.07 version :(

**Comment by poliva** [comment]
Clossing issue. At the moment not possible with the current ggpofba emulator on FightCade. If we change that in the future it might be supported.
