### ISSUE TITLE
X-Men: Children of the Atom Change

### ISSUE THREAD

**Issue by hotboilivejive** [poliva/fightcadestates#57]
Change to USA (english)
Change to freeplay

Thank you

**Comment by 3xcl4m4t10n** [comment]
If my memory is OK, COTA can't be change to english or freeplay. The changes are not going to save on the savestate, but in the .cfg  and FightCade do not synch the cfg only the savestates so is a no-way by now.

**Comment by hotboilivejive** [comment]
that's a bummer.....y not sync cfg files???

**Comment by 3xcl4m4t10n** [comment]
Because no XD. P0f did not make it but we was discussing about this long time ago so maybe in a future he make it. But don't expect it soon :)

**Comment by hotboilivejive** [comment]
you dumby dumbs......*le sigh*.....smh....xD


NOW GET MVC2 ON THERE BITCHES

**Comment by 3xcl4m4t10n** [comment]
MVC2 is Naomi:

https://en.wikipedia.org/wiki/Marvel_vs._Capcom_2:_New_Age_of_Heroes

Read this article:

https://en.wikipedia.org/wiki/Arcade_system_board

And then you can check the list of supported boards of FBA.

**Comment by hotboilivejive** [comment]
I know it's not supported. I'm saying change that lol. >;)
