### ISSUE TITLE
Fightcade's Final Burn Alpha

### ISSUE THREAD

**Issue by Woon4X** [poliva/fightcadestates#58]
So on the FAQs you said that you will consider updating the Final Burn Alpha version's which Fightcade is currently using (ver. 0.2.96.74). I am not gonna ask when you will do it (even though it would be really cool to announce it, you know? :) ). Anyway what i wanna ask is are you gonna update it to the latest version which Final Burn Alpha website's has right now (version 0.2.97.36 if i remember...) or are you gonna update it to it's next version version? Version 0.2.96.75 i think/maybe?

**Comment by poliva** [comment]
It won't probably be latest version, or at least not if we plan to reuse the ggponet.lib provided in ggpofba source. I've tried building some newer versions in the 0.2.96.xx but I always encountered issues: sound not working in some games, graphical glitches in others, cps3 support totally broken, etc...

**Comment by 3xcl4m4t10n** [comment]
That's sad @poliva. Did you thought to contact with FBA team for help? Or are this issues that can't be solved?

**Comment by poliva** [comment]
update, to the latest version coming soon. No ETA yet, but we're working on it.
