### ISSUE TITLE
Street Fighter 3 third strike v042.2

### ISSUE THREAD

**Issue by Presipizle** [poliva/fightcadestates#59]
After I installed Fightcade v042.2, my Street fighter 3 third Strike ROM stopped working. The specific ROMs I have are sfiii3, sfiii3n, and sfiii3an, and non of them have been working. This is the error message I keep receiving  
![problem](https://cloud.githubusercontent.com/assets/13687598/9702208/f2bf84a8-5421-11e5-8c0f-d787731d4191.JPG) 
please let me know if there is anything I can do to fix this problem.

**Comment by hanasu** [comment]
You're missing (or have the wrong version) of sfiii3n.zip for a start. Get that and see what happens.
