### ISSUE TITLE
New game request - Street Fighter III 4rd Strike Arrange Edition 2013

### ISSUE THREAD

**Issue by kenuran** [poliva/fightcadestates#60]
I wish to request a room for the 2013 rom hack of SF3: 3rd Strike made by zsnsn. See Youtube vids for details:
https://www.youtube.com/watch?v=zenJc7DM_Mk 
https://www.youtube.com/watch?v=NjbQcF7B1u4 
https://www.youtube.com/watch?v=FAa5AoXw9fk

The game runs off a hacked version of the sfiii3an.zip rom. Not to be confused with the 2011 rom hack Street Fighter III 4th Strike.
 
I already tested it in the unsupported room with wuziq last night and was able to get the game running on Fightcade. 

If you want to test it yourself here is the game: http://www.mediafire.com/download/q47gnn5ob57jax2/sfiii3an.zip 
Here is the savestate: http://www.mediafire.com/download/9yaq4f9z3l5yzvj/unsupported_ggpo.fs

To run the game, make sure that the original game's or the 4th Strike rom (also sfiii3an.zip) is renamed or moved out of the same roms folder as the hacked sfiii3an.zip rom.

If you make the room could you link the Youtube videos about the game and point people to this pastebin detailing how to play: http://pastebin.com/XewURbVY

**Comment by poliva** [comment]
https://github.com/poliva/pyqtggpo/issues/39
