### ISSUE TITLE
3 Player Request (I know it's P2P)

### ISSUE THREAD

**Issue by yaragad** [poliva/fightcadestates#61]
First, congratulations as this is the best online emulator ever.
And, ok, I know this is a P2P, but, is it possible to implement 2 player on one site and 1 player on the other? I'm playing King of Dragons, but, when we start the online game, only 2 player are allowed. I think you can set not just the "remote attack" button but "attack P1" and "attack P2" and player 3 is in the other place.
Is it possible?
Thanks in advance.

**Comment by poliva** [comment]
sorry not possible, the underlying protocol (GGPO) only supports 2 players.
