### ISSUE TITLE
Fightcade in OSx El capitan, is not work

### ISSUE THREAD

**Issue by neoyukito** [poliva/fightcadestates#62]
Os El capitan Version 10.11.1

Message: "The application "fightcade.app" can't be opened.

**Comment by poliva** [comment]
System Preferences --> Security & Privacy --> General --> Allow apps downloaded from: Mac App store and identified developers 

https://twitter.com/FightCade/status/661106168820064256

**Comment by neoyukito** [comment]
I have this configuration:
<img width="668" alt="screen shot 2015-11-14 at 23 00 14" src="https://cloud.githubusercontent.com/assets/5897215/11166765/7815a1ae-8b23-11e5-98f0-da5eebe8b562.png">

with this error:
<img width="422" alt="screen shot 2015-11-14 at 22 56 55" src="https://cloud.githubusercontent.com/assets/5897215/11166762/52782c50-8b23-11e5-949a-f69d87cf7808.png">

Furthermore, the application did not throw a log file, so you can check the technical information for error.
