### ISSUE TITLE
Power Drift Addition [Request]

### ISSUE THREAD

**Issue by ChristyKomiya** [poliva/fightcadestates#63]
Hello, I would like to request Power Drift be added to Fightcade. I've already tested it and it works. The only thing wrong is that there are improper (yet minor) button commands. For example: Instead of your usual arrow button assignments, it's replaced with a steering button assignment which isn't responsive for controller support. If that can be fixed with the games official addition then it would be good to go.

http://www.mediafire.com/download/xw8tb2u14jpapw4/pdrift_ggpo.fs <--- Here is the savestate.
http://www.mediafire.com/download/e53284oqj1oa5ym/pdrift.zip <--- Here is the zip itself.

**Comment by poliva** [comment]
Added to fightcade, should be live the next time the server is restarted.

**Comment by ChristyKomiya** [comment]
Nice and thank you! So when will the server get restarted?

**Comment by poliva** [comment]
just restarted it right now. Game is now available on the list: http://www.fightcade.com/game/pdrift

**Comment by ChristyKomiya** [comment]
Thank you very much!＾＾
