### ISSUE TITLE
Stuck on "Connecting to server" when challenging anyone, can't spectate/watch replays (Win 10 64 bit)

### ISSUE THREAD

**Issue by erythrocytes** [poliva/fightcadestates#66]
Hi, I'm trying to get Fightcade to work on Windows 10 (Bootcamp).

I have Macbook Pro with both OS X and Windows 10 installed. In OS X port, Fightcade works well, but the emulator itself is pretty sloppy.

So I decided to use the Windows version instead. The emulator works well, but I can neither spectate nor challenge anyone. When I make/accept a challenge, all I get is a screen with Fightcade logo saying "connecting to server". And it gets stuck on it.

So I read in many places I should open up ports for Fightcade, UDP 6000-6009 and TCP 7000. I'm not a big Windows fan but I figured how to add the rules to the firewall. I made them for both inbould and outbound traffic. Still nothing.

I tried turning off the firewall, also reinstalling Fightcade. The issue still persists. The only thing I haven't done is try to open ports in my router yet, but if on OS X it worked fine, I don't know if it will help.

What should I even do at this point?

**Comment by poliva** [comment]
Open ggpofba (without starting any game), enable sound: In the sound menu, make sure the option 22050Hz is marked. Close ggpofba. Done.

**Comment by erythrocytes** [comment]
Thanks you very much!

**Comment by Adelslg1** [comment]
You saved me polivia. you are a genius. I've been trying all the difficult solutions and toturials and nothing worked. Once I clicked that frequency magical button and suddenly  everything's okay. Thanks very much you made my day ;)

**Comment by Chewhern** [comment]
Me and my brother are trying to play game on FIghtCade too, but I have these 2 errors 1 is connecting to server and after maximize it says "Retrieving match info". We both share the same internet.

**Comment by catalaman** [comment]
hello everybody im new here ,someone can help me ,  when /challege or accept wont start the fight the game window won't show .
the problem is not my internet or nor my firewall because everything was good i had this prblm just this week

**Comment by Abhinandan-Ricky** [comment]
The solution doesn't work

**Comment by catalaman** [comment]
which solution are you talkin about ?????

**Comment by Abhinandan-Ricky** [comment]
That 'enable sound 22500hz'

Best Regards,

*Abhinandan Dey*
Junior Photogrammetrist
Cell: +8801680170465

Flat 1B, Holding No.: 8/4A,
Block-B, Lalmatia, Dhaka 1207
www.magpie-robin.com
