### ISSUE TITLE
Controller inputs not recognized

### ISSUE THREAD

**Issue by Jamnetic** [poliva/fightcadestates#72]
I have a MadCatz PS3 Tournament Edition Fightstick that is recognized by Windows 7 (While plugged into a USB port using an Intel chipset USB controller only). It shows up as a PC USB Wired Stick 8838 in the Game Controllers setup tool in Windows 7. When I start up SNK vs Capcom Chaos Plus in Fightcade however and try to map my buttons no input on the joystick is recognized despite it being shown working in the windows config tool. It also works in other programs like JoyToKey. Am I missing something here or is it just not supported?

**Comment by 3xcl4m4t10n** [comment]
- Do you input the pad before start final burn alpha?
- Did you try x360ce?

BTW, never heard issues with that stick, and it is a pretty common used stick...
