### ISSUE TITLE
Fightcade is not work on Win7 64bit

### ISSUE THREAD

**Issue by baga73** [poliva/fightcadestates#74]
as title how can I fix it?

**Comment by 3xcl4m4t10n** [comment]
There's nothing to fix because it works perfectly on Win7 64bits :D.

**Comment by baga73** [comment]
but I couldn't open it. When I click fightcade.exe nothing happened.

**Comment by 3xcl4m4t10n** [comment]
Then you have some several issues with your computer.

**Comment by tienhuu1408** [comment]
@3xcl4m4t10n I have the same problem with @baga73 when running fightcade.exe in Windows 7 Enterprise 64bit, nothing happened although it worked fine on Windows XP SP3 x86. Hope you could help me!

**Comment by poliva** [comment]
check that your anti-virus or security software is not blocking execution of fightcade. It works fine on Win7 64bit.

**Comment by nicholas-barcelos** [comment]
I play fightcade for years and now out of the blue I'm Having the same issue.

Even downloaded again on the site, still having the same trouble.

Edit: Unistalled AntiVirus(don't have anything else of the kind), Reboot, Download Again, Extract to Different Folder, same error
