### ISSUE TITLE
CANT accept match and send challenge FAILED

### ISSUE THREAD

**Issue by tyci123** [poliva/fightcadestates#76]
Ever since the v042.2 update I cant play a match . I have all the correct roms . My directory appears to be located . When a challenge comes clicking accept does nothing and if I challenge someone it immediately says send challenge failed . Please help .

**Comment by 3xcl4m4t10n** [comment]
Disable any antivirus/firewall/antimalware you have. Make sure you have all the updates of your OS. Forward the old ports on your router.

**Comment by catalaman** [comment]
hello everybody im new here ,someone can help me ,  when /challege or accept wont start the fight the game window won't show .
the problem is not my internet or nor my firewall because everything was good i had this prblm just this week
