### ISSUE TITLE
Player SEMIVERDADEIRO disrespecting

### ISSUE THREAD

**Issue by Wall-Garants** [poliva/fightcadestates#77]
This player is disrespecting the other players, please take providences.
https://lh3.googleusercontent.com/-mA5MlAr-J18/VwB18IEhHfI/AAAAAAAAA0I/XBwkJHoUOGI4Et_mKhY67ZK9utRv3nDtQCCo/s912-Ic42/Sem%2Bt%25C3%25ADtulo.png

**Comment by 3xcl4m4t10n** [comment]
This is not the site to put this kind of things. You can publish it here:

https://www.reddit.com/r/Fightcade/

Anyway there's no moderation at this moment on Fightcade. If someone is bothering you you can block him.

**Comment by Wall-Garants** [comment]
Thanks friends
