### ISSUE TITLE
Username change?

### ISSUE THREAD

**Issue by Aria-N** [poliva/fightcadestates#78]
Hello!.
Would it be possible to have my FightCade username changed _without_ creating a new account?
I already know that there is no option for users to change username or password in the site, but...if it is just the username, would it be possible for an administrator to change it?

**Comment by poliva** [comment]
no, sorry that is not possible.

**Comment by Aria-N** [comment]
That's too bad...but thanks for answering. =)

**Comment by Arm4GeDon** [comment]
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHH
