### ISSUE TITLE
Jojo suddenly closing 

### ISSUE THREAD

**Issue by tib414** [poliva/fightcadestates#8]
Hello~
Don't know if this issue is ONLY for Jojo but~ The issue is I'm playing with my friend normally and suddenly the emulador close without any warning...
This is the only issue we have found while playing jojo and it is really annoying ;_;
Hopefully it helps, you can contact me on twitter too (@tib_n)
Waiting for responses, thanks :3

**Comment by tib414** [comment]
I'm getting this problem with sf3 third strike too =(

**Comment by poliva** [comment]
probably an issue in your connection, or your peer's connection. Once the game starts, it is p2p between the two players, the server has nothing to do if the game crashes while the two players are playing.
